<a href="https://colab.research.google.com/github/swatijain200701-sys/AI-ML-Skills-/blob/main/swati's_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy arrays + basic operations



Why to use numpy?


1.   provides efficient storage.
2.   Better way of handling data for procrssing.
3.  It is fast, easy to lear. uses relatively less memory to store data.   






In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print("COMPLETE ARRAY",arr)
print("FOR SINGLE DIMENTIONAL ARRAY",arr[4])
arr1=np.array([[1,2,3,4,5,6]])
print("FOR MULTI DIMENTIONAL ARRAY: ", arr1[0,5])



COMPLETE ARRAY [1 2 3 4 5 6]
FOR SINGLE DIMENTIONAL ARRAY 5
FOR MULTI DIMENTIONAL ARRAY:  6


**Array creation: Conversion from other Python structures**

In [ ]:
#list in array using numpy
import numpy as np
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(listarray)
#to change any number in any position
listarray[2,2]=5
print(listarray)
#to know interger type,shape(matrix),size(number of elements)
print(listarray.dtype)
print(listarray.size)
print(listarray.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 5]]
int64
9
(3, 3)


mainly when every we need we use interger or float type array rather then dictionay or list or tuple.

There are 5 general mechanisms for creating arrays:
Arrays
1. Conversion from other Python structures (e g. lists, tuples)
2. Intrinsic numpy array creation objects (e g, arange, ones, zeros, etc.)NumPy
3. Reading arrays from disk, either from standard or custom formats
Array
4. Creating arrays from raw bytes through the use of strings or buffers
Creation
5. Use of special library functions (e.g., random)

In [ ]:
#to print matrix of 0's
import numpy as np
zeros=np.zeros((3,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#to enter range
import numpy as np
range = np.arange(5,15,2) #any range can be given ("where to start" , "where to end" , "increment")
print(range)
#to get equally spaced/gap/difference numbers
gap = np.linspace(1,50,10)
print(gap)
#to print identity matrix
identity_matrix = np.identity(5)
print(identity_matrix)
#to print empty matrix
empty_matrix = np.empty((4,6))
print(empty_matrix)
#to reshape
arr = np.arange(99)
print(arr)
arr = arr.reshape(3,33)
print(arr)
#to arrange properly
ravel=np.ravel(arr)
print(ravel)


[ 5  7  9 11 13]
[ 1.          6.44444444 11.88888889 17.33333333 22.77777778 28.22222222
 33.66666667 39.11111111 44.55555556 50.        ]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[-0.25 -0.5   0.   -0.25  0.25 -0.5 ]
 [ 0.5  -0.25  0.25  0.    0.5   0.25]
 [ 0.25  0.5   0.    0.25 -0.25  0.5 ]
 [-0.5   0.25 -0.25  0.   -0.5  -0.25]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 9

**NUMPY AXIS**

In an numpy array '2D' matrix the ROW is 'axis0' and COLOUM is 'axis1'.


In [ ]:
import numpy as np
x = [[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(x)
#to get sum of any particular axis
sum=arr.sum(axis=1)
print(sum)
#to transpose any arr
print("the original array: \n",arr)
print("the transpose of the array is: \n",arr.T)
#to get all element
for items in arr.flat:
  print(items)
#to know the number of axis
print(arr.ndim)
#to know how many bytes is the array is consuming
print(arr.nbytes)


[ 6 15 24]
the original array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
the transpose of the array is: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
1
2
3
4
5
6
7
8
9
2
72


**Different types of methods**

argmax :- to access max value from the array.

argmin :- to access min value from the array.

argsort :- to sort the array in assesding order

In [ ]:
#for 1D array
import numpy as np
arr=np.array([1,11,8,3,5,6])
print(arr.argmax())  #will give the index of the min/max number from the array
print(arr.argmin())
print(arr.argsort())


1
0
[0 3 4 5 2 1]


**For 2D Array**


In [ ]:
#all the outputs are showing the indexs for the desired results
import numpy as np
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d.argmax())
#to get max or min value from any particular axis
print(arr2d.argmax(axis=0))
print(arr2d.argmax(axis=1))
print(arr2d.argmin(axis=0))
print(arr2d.argmin(axis=1))
#to sort the 2D array
print(arr2d.argsort(axis=0))
print(arr2d.argsort(axis=1))


8
[2 2 2]
[2 2 2]
[0 0 0]
[0 0 0]
[[0 0 0]
 [1 1 1]
 [2 2 2]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


**Mathematical Oprations that are allowed with the use of NUMPY library:-**

In [ ]:
#TO SUM
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1+arr2) #the value at same index of both the arrays with sum up and final added array will be formed
#TO SUBTRACT
print(arr1-arr2)
#TO MULTIPLY
print(arr1*arr2)
#TO DIVIDE
print(arr1/arr2)


#FOR SQRT(to get under root )
print(np.sqrt(arr1)) #will return underroot of all the values of matrix arr1
#to find any element
print(np.where(arr1>5))
#to count non zero element
print(np.nonzero(arr1))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
(array([1, 2, 2, 2]), array([2, 0, 1, 2]))
(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))


**Proof How numpy takes less space**


In [ ]:
import numpy as np
import sys
py_ar=[0,4,55,2]
arr=np.array(py_ar)
#to get size of one element of the array
print(sys.getsizeof(1)*len(py_ar))
#the bytes with nupy array
print(arr.itemsize*arr.size)


112
32


There are multiple 'methods' and 'attributes' in numpy array to get and learn more about the same go to the official website "SciPy.org" .